### ISSUE TITLE
Gov Delivery moved image need to update so images shows

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-Employment#4]
New link code - `https://public.govdelivery.com/assets/required-139b548414c88442cfc0772133ef4b70da67b21046b31a86cea9bf6a0dc7c9d3.gif`

**Comment by vwolfley** [comment]
replaced image and pushed

**Comment by Jfairfield1** [comment]
Looks like they moved it again.  Maybe we should download a required image and use that instead.

**Comment by vwolfley** [comment]
I think that would be a good idea.

**Comment by Jfairfield1** [comment]
Found a permanent link to this image.  Should have used this from the start.

https://public.govdelivery.com/static/required.gif
